### PR TITLE
WIP Configure Satis repository when enabling extension

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
It's not working at the moment, I'm getting 403 errors from the satis endpoint when enabled :(

Also, there's a quiet issue if a "repositories" key is present in composer.json but uses an array instead of an object (we need to name our repo so it can be easily found & replaced when enabling the extension)

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
Didn't notice your `satis` branch, my bad 🙈

I will try to merge all this in a single PR

**Comment by Luceos** [comment]
Confirmed that this only works if "repositories" is an object, not an array, we have to mutate all items in that list to become an object (perhaps based on the path?)

**Comment by Luceos** [comment]
fixed the 403 by putting the token and Bearer witin single quotes

**Comment by Luceos** [comment]
Going to add further logic in a new branch, let's move on with this.

**Pull request merged**
