### PR TITLE
WIP Premium packages; Bazaar

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
**Work in progress**

Private packages implementation

flagrow.io counterpart in https://github.com/gravure/flagrow.io/pull/7

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
If we mark a normal package premium in flagrow.io it looks like Bazaar uses our Satis endpoint to download it, which works fine.

However when trying to install premium packages which are not in Packagist, Bazaar fails with the message `Package "flagrow/dummy-premium-one" listed for update is not installed. Ignoring`.

Using `composer require flagrow/dummy-premium-one` by hand in the same install works without issue.

Ping @luceos if you want to test. You need both this branch of bazaar and the linked branch of flagrow.io

Additional note: When the case above happens, Composer does not fail. because that's just a warning. Instead the controller fails when trying to return the data about the installed package. Because it happens in an ApiController, beta6 only returns an "Internal Server Error" string. core dev-master displays the full error message (which is just null returned instead of the Extension)

**Comment by clarkwinkelmann** [comment]
Finally fixed the two issue preventing installation of satis packages.

First, the code looking for package versions wasn't using the repos from the `composer.json` file but only the default one (In other words, only from Packagist)

I fixed the first issue by re-using the `Composer` client, but we need to refresh it after we changed `composer.json`.

We could do some fancy `Composer` stuff to tell it which packages we added, but it's maybe safer to re-create a new one. That's what happened before already, except it wasn't created by Bazaar and didn't load the `composer.json` correctly.

I added unit tests for Satis install by the way. I had to find a way to simulate HTTP requests for Composer. I went with a [solution I found on SO](https://stackoverflow.com/questions/13136275/how-to-start-and-stop-php-dev-server-with-exec) using the PHP dev server. It probably has no change to work on Windows.

Maybe it's possible to mock HTTP requests for Composer, but I'm not sure how. This would require more research.

**Comment by luceos** [comment]
Is this ready for the final review @clarkwinkelmann ?

**Comment by clarkwinkelmann** [comment]
Not quite yet @luceos 

I still need to make it user-friendly if you're not connected to flagrow.io or are not a premium user (aka user with a credit card)

Also I might make some changes as I finish work on flagrow.io

**Comment by clarkwinkelmann** [comment]
Note to self: I probably misunderstood how badges work :joy: 

I'll fix it soon.

image

**Comment by clarkwinkelmann** [comment]
Note to self: package state is not updated after an extension is bought via the new popup

**Comment by clarkwinkelmann** [comment]
@flagrow/gravure did somebody try this PR ? Are we still missing something ?

As I said somewhere else it could do with some relooking but it's ready feature-wise (unless the team feature breaks it ? But I don't think so)

Maybe I should just make sure it doesn't break if flagrow.io doesn't offer any premium extension and merge it so we can move forward ? I think it currently assumes a few new feature from flagrow.io

**Comment by luceos** [comment]
@clarkwinkelmann let's do that, just try it with your current dev flagrow then merge. We need to do  a test drive with premium teams before releasing bazaar and flagrow anyway.

**Pull request merged**
